### ISSUE TITLE
Can I get some help?

### ISSUE THREAD

**Issue by enerbewow** [BeepIsla/CSGO-MajorVotes#2]
I'm so happy to find this plugin.
I love it and I really want to use, but the problem is with 3 command:
sm_tournament_enabled - it's always 1 by default.
and this cause more problems. it's always sm_tournament_name "CSGO_Tournament_Event_Name_14"
sm_tournament_stage "CSGO_Tournament_Event_Stage_Display_32"

is anything to do with that? Voting barely working.

**Comment by BeepIsla** [comment]
Been a while since I looked at the plugin. Every major Valve changes some things in the back and doesn't let anyone know because they don't expect anyone to use it.

I will take a look and see if there are any issues.

**Comment by enerbewow** [comment]
I am glad you made this. I hope someday they make OpenSource those things like GSI

**Comment by BeepIsla** [comment]
> sm_tournament_enabled - it's always 1 by default.
>and this cause more problems. it's always sm_tournament_name "CSGO_Tournament_Event_Name_14"
>sm_tournament_stage "CSGO_Tournament_Event_Stage_Display_32"

Where did you edit those value? The plugin runs the config stored in the sourcemod folder upon loading. (`csgo/cfg/sourcemod/tournament.cfg`, if the file does not exist it will automatically create it)

**Comment by enerbewow** [comment]
> > sm_tournament_enabled - it's always 1 by default.
> > and this cause more problems. it's always sm_tournament_name "CSGO_Tournament_Event_Name_14"
> > sm_tournament_stage "CSGO_Tournament_Event_Stage_Display_32"
> 
> Where did you edit those value? The plugin runs the config stored in the sourcemod folder upon loading. (`csgo/cfg/sourcemod/tournament.cfg`, if the file does not exist it will automatically create it)

I didn't know that. I tought I need to exec the config, but when I did that it's always change back to defaults. That's good to know 👍  :)

**Comment by BeepIsla** [comment]
Try editing that file instead and see if it fixes your issue

**Comment by enerbewow** [comment]
Yeah. it's ok now. Is there any way to create custom Stage or Event_Name? I tried to rename in csgo_english.txt. It won't worked :D

**Comment by BeepIsla** [comment]
Not that I know of. As far as I know you are forced to use values from csgo_english.txt.

Editing it and creating your own key values might work but then other clients who connect to your server do not see it so its not a good solution.

Pre-Panorama you were able to use custom names but it doesn't look like that works anymore, sadly.

What you can do though is just set the tournament name to something random, that way it doesn't show the tournament name but still has the stage displayed. It doesn't look *as* nice but I guess its better than nothing.

**Comment by enerbewow** [comment]
Yeah sadly :(
Is there anyway (plugin) to get back the teammenu?
I found a way to force players to join CT or T by STEAMID3

**Comment by BeepIsla** [comment]
Not as far as I know. The team menu is forcefully disabled as soon as we set the required netprops for the votes.

**Comment by enerbewow** [comment]
can this help? https://github.com/SlidyBat/sendproxy or https://forums.alliedmods.net/showthread.php?t=169795

**Comment by BeepIsla** [comment]
I don't know, I would just use a team manager of some sort and done. The forum post doesn't make it look like it will work on CSGO.

>This extension only works on and is only supported on the following engines: ep2, ep2v, and css.
