### ISSUE TITLE
Voting System since the last update not working anymore

### ISSUE THREAD

**Issue by NeXiDE** [BeepIsla/CSGO-MajorVotes#4]
Since the newest update (v3.0)
It is not possible to vote for anything else then voting for a timeout

Readding the functions would be a fix in my eyes

**Comment by BeepIsla** [comment]
Any errors?

What happens? Nothing?

What does `listissues` in the console (On the client) output?

**Comment by NeXiDE** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/66691455/97498322-47ff2d00-196c-11eb-97c2-8aef5c2b25c5.png)
![Screenshot_14](https://user-images.githubusercontent.com/66691455/97498325-47ff2d00-196c-11eb-8e68-68ddfc94f9dd.png)
listissues doesn't give out the other votes

**Comment by BeepIsla** [comment]
What does `sm plugins list` on the server output? Is the plugin loaded correctly?

**Comment by NeXiDE** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/66691455/97498720-f6a36d80-196c-11eb-89ae-666a015643e0.png)
![Screenshot_17](https://user-images.githubusercontent.com/66691455/97498723-f6a36d80-196c-11eb-9c80-d6bd417d81db.png)
First Screenshot is when checking with sm plugins list
Second one is after reloading it. No error outputs or anything

**Comment by BeepIsla** [comment]
What happens when you run `sm_match_reload` on the server?

**Comment by NeXiDE** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/66691455/97499003-703b5b80-196d-11eb-8003-bb749aac50be.png)
Still no error

EDIT: The player getting on the right team still works though

**Comment by BeepIsla** [comment]
Try joining the server *then* typing `mp_match_reload`. If that doesn't work try starting the server using the `-tournament 1` launch option.

In my test just now it turns out that the required vote handling doesn't load on map change anymore, it only loads on server start I guess? So you must start the server using that launch parameter for everything to work it seems like.

**Comment by NeXiDE** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/66691455/97500903-b47c2b00-1970-11eb-83a3-bbe68c7aa70b.png)
Adding `-tournament 1` did the Job
This should either be added to the documentation of be forced somehow
Thanks for the fast help

**Comment by BeepIsla** [comment]
> or be forced somehow

It does that https://github.com/BeepIsla/CSGO-MajorVotes/blob/468ae714a10a731a7cf37d08aa352616d465f8bb/plugin.sp#L108-L116

It just doesn't seem to work anymore?

**Comment by NeXiDE** [comment]
Could be. 
Saw that code already before but apperantly is not working anymore

EDIT: Maybe because `ExtendedCommandLine_Remove("-tournament");` can't find the `tournament` parameter?

**Comment by BeepIsla** [comment]
I will just put it in the README for now

**Comment by BeepIsla** [comment]
It used to work I think. Unless my testing server back then always had `-tournament` and I never realized.

I don't think `ExtendedCommandLine_Remove` is the issue, if I read [this](https://github.com/perilouswithadollarsign/cstrike15_src/blob/29e4c1fda9698d5cebcdaf1a0de4b829fa149bf8/tier0/commandline.cpp#L323-L392) code correctly then it just won't do anything if it can't find it.

**Comment by NeXiDE** [comment]
Yeah just gone through it. You are right.
Atleast it is in the documentation for now. That's what counts
